
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/pip-build-env-i3340lxt/overlay/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.10.102.1-microsoft-standard-WSL2 - x86_64
...
